name: xapptor_community
description: Module to create user communities.
# repository: https://github.com/Xapptor/xapptor_community
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: ">=3.1.0 <5.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_storage: ^13.0.4

  google_fonts: ^6.3.2
  universal_platform: ^1.1.0
  pdf: ^3.11.3
  printing: ^5.14.2
  file_picker: ^10.3.7
  flutter_colorpicker: ^1.1.0
  intl: ^0.20.2
  http: ^1.6.0
  font_awesome_flutter: ^10.12.0
  flutter_expandable_fab: ^2.5.2
  fl_chart: ^1.1.1
  carousel_slider: ^5.1.1
  camera: ^0.11.3
  video_player: ^2.10.1
  just_audio: ^0.10.5
  confetti: ^0.8.0

  # xapptor_logic: ^0.0.3
  # xapptor_router: ^0.0.2
  # xapptor_translation: ^0.0.3
  # xapptor_ui: ^0.0.3

  xapptor_db:
    path: ../xapptor_db
  xapptor_logic:
    path: ../xapptor_logic
  xapptor_router:
    path: ../xapptor_router
  xapptor_translation:
    path: ../xapptor_translation
  xapptor_ui:
    path: ../xapptor_ui

dependency_overrides:
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
